.PHONY: clean All

All:
	@echo "==========Building project:[ Lesson1 - Debug ]----------"
	@cd "Lesson1" && "$(MAKE)" -f  "Lesson1.mk"
clean:
	@echo "==========Cleaning project:[ Lesson1 - Debug ]----------"
	@cd "Lesson1" && "$(MAKE)" -f  "Lesson1.mk" clean
